In [5]:
import torch

q = torch.randn((3,2))
q

tensor([[ 1.0052,  1.8757],
        [ 0.6484,  0.0041],
        [-1.4124, -2.0262]])

In [27]:
k = torch.randn((4,3,2))
k.shape

torch.Size([4, 3, 2])

In [28]:
a = k.transpose(-2,-1)
a.shape

torch.Size([4, 2, 3])

In [31]:
b = k.transpose(-1,-3)
b.shape

torch.Size([2, 3, 4])

In [53]:
x = torch.zeros(2,1,3,1)
print(x)
x.shape


tensor([[[[0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.]]]])


torch.Size([2, 1, 3, 1])

In [58]:
x_s = x.squeeze()
print(x_s)
x_s.shape


tensor([[[0., 0., 0.]],

        [[0., 0., 0.]]])


torch.Size([2, 1, 3])

In [60]:
x_us = x_s.unsqueeze(3)
print(x_us)
x_us.shape

tensor([[[[0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.]]]])


torch.Size([2, 1, 3, 1])